version: '3.1'

services:
  db:
    image: mysql:8.1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: file_storage
      MYSQL_USER: nastya
      MYSQL_PASSWORD: 1234
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=1234
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: nastya_user
      MINIO_ROOT_PASSWORD: strong_password123
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}