version: '3.1'

services:
  db:
    image: mysql:8.1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: file_storage
      MYSQL_USER: nastya
      MYSQL_PASSWORD: 1234
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=1234
      - REDIS_PORT=6379
      - REDIS_DATABASES=16